name: CMake build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang, cl]
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v4

      - name: Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y xorg-dev libwayland-dev libxkbcommon-dev wayland-protocols

      - name: Configure CMake
        run: |
          if [[ "${{ matrix.c_compiler }}" == "gcc" ]]; then
            CXX=g++
          elif [[ "${{ matrix.c_compiler }}" == "clang" ]]; then
            CXX=clang++
          else
            CXX=cl
          fi

          cmake -B build \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -S "$GITHUB_WORKSPACE"
        shell: bash

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j4
